version: '3'

services:
  app:
    depends_on:
      - 'postgres'
    image: 'teamsnap/adsnap-admin:latest'
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    environment:
      SECRET_KEY_BASE:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/adsnapadmin

  postgres:
    image: 'postgres:13.4'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: adsnapadmin

volumes:
  postgres:
